### ISSUE TITLE
pkgdown deployment issues

### ISSUE THREAD

**Issue by lcolladotor** [pachterlab/museumst#1]
Hi Lamba,

I was looking at this repo during your #BioC2020 talk. Thanks for listing our pre-print as your latest "major event" (first Visium pre-print) at https://docs.google.com/spreadsheets/d/1sJDb9B7AtYmfKv4-m8XR7uc3XXw_k4kGSout8cqZ8bY/edit#gid=1693202466. 

I was trying to find the `pkgdown` website for your repo at http://pachterlab.github.io/museumst/ but I see the error at https://github.com/pachterlab/museumst/runs/924246430?check_suite_focus=true#step:9:100 which you can fix by using the lines of code at https://github.com/lcolladotor/biocthis/blob/master/actions/check-bioc.yml#L276-L286. You might also be interested in `biocthis` anyway, though I need to work a bit more on it.

Best,
Leo

**Comment by lambdamoses** [comment]
Thank you for the suggestion. Now the pkgdown website builds, though it's now in development mode as I still need to work on the documentation.
