### ISSUE TITLE
Cannot access website

### ISSUE THREAD

**Issue by jasperhyp** [pachterlab/museumst#2]
Dear Authors,   Thanks for your wonderful work!  It has helped me a lot in understanding the different aspects of spatially-resolved RNA-seq methods.  However when attempting to access your website [musemst](https://bookdown.org/lambdamoses/museumst/) today it gave me an error `404 page not found`.  Would the website be open soon?

Thanks!

**Comment by lambdamoses** [comment]
The website has been moved to here: https://pachterlab.github.io/LP_2021/
